version: '0'

services:

  mySQLEnvoirment:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_User: Python
      MYSQL_PASSWORD: Python
      MYSQL_DATABASE: Reddit
    ports:
      - "3308:3306"


networks:
  liitleNetwork:
    driver: custom-driver-1